apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aircraft-ms
  name: aircraft-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aircraft-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aircraft-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-462305/aeoroline/aircraft-ms
        name: aircraft-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          value: "file:./dev.db"
        resources: {}
status: {}
